### PR TITLE
0.2.1 release notes

### PR DESCRIPTION
**Pull request by n0rdlicht**

### CODE REVIEW

**Review by LKajan — APPROVED** [review]
The changelog looks good to me. I added a commit to update the download link in readme.
Are we ready for the release?

**Comment by LKajan** [comment]
@n0rdlicht , I made the release now but I just noticed that it has been you how has done it before. Hopefully it was not too early or didn't otherwise break the rules too bad 😟.

**Comment by LKajan** [comment]
Well, the release action failed. Perhaps only you have privileges to upload the plugin to the qgis plugin repo. Could you @n0rdlicht 
 try to re run the failed action?

**Comment by n0rdlicht** [comment]
I think the action is broken because of an upstream issue with the plugin repo @Joonalai was tracking back then. Last releases we uploaded manually, which I can do if you think everything else is looking good.

Edit: did an upload on the plugin repository, pending approval.

**Pull request merged**
