### PR TITLE
UI for snapshot contributors

### LINKED ISSUE #44: Add UI for editing snapshot contributors
**Expected behaviour**
Similar to adding layers and sources, adding and managing contributors could work as an extra section at the bottom of the UI stack (after bounds).

**Current behaviour**
Each contributor has the following properties (cf. https://specs.frictionlessdata.io/data-package/#contributors):
- role: one of `author`, `publisher`, `maintainer`, `wrangler`, or `contributor` (default)
- title: String (e.g. first- and lastname) – required
- email: String (e-mail) – optional
- path: String (url) – optional
- organisation: String – optional

**Additional context**
The resulting array of dictionaries (with aboves structure) are written to `snapshot.contributor`.

### PR DESCRIPTION
**Pull request by Joonalai**
This PR:
- Add contributor editing possibility to UI
- Makes some contributor fields optional
- Add [flake8-qgis](https://github.com/GispoCoding/flake8-qgis) to pre-commit
- Add imported layers to dock widget if they exist on the project (the data import comes with #49) 

Resolves #44.

### CODE REVIEW

**Comment by Joonalai** [comment]
@n0rdlicht here is a PR plugin if you want to test this
[SpatialDataPackageExport.44.zip](https://github.com/cividi/spatial-data-package-export/files/6700818/SpatialDataPackageExport.44.zip).

**Comment by n0rdlicht** [comment]
Thanks @Joonalai. Looks good and seems to be working well, also regarding utf-8 compatibility of layer data :)

Two small things:
- layers seem to be missing when loading a snapshot from the project file, same happens when loading from a snapshot file from disk, any idea?
- the template files are automatically replaced when installing a new version to avoid conflicts, right?

**Review by n0rdlicht — CHANGES_REQUESTED** [review]
Thanks @Joonalai. Looks good and seems to be working well, also regarding utf-8 compatibility of layer data :)

Two small things:
- layers seem to be missing when loading a snapshot from the project file, same happens when loading from a snapshot file from disk, any idea?
- the template files are automatically replaced when installing a new version to avoid conflicts, right?

**Comment by Joonalai** [comment]
>     * the template files are automatically replaced when installing a new version to avoid conflicts, right?
Yes, the default templates will be overwritten. However, as new fields are optional, old templates should work just fine :)

**Comment by Joonalai** [comment]
@n0rdlicht here is a test plugin that you could test this PR with:
[SpatialDataPackageExport.44_2.zip](https://github.com/cividi/spatial-data-package-export/files/6708846/SpatialDataPackageExport.44_2.zip)

**Comment by n0rdlicht** [comment]
> @n0rdlicht here is a test plugin that you could test this PR with:
> 
> [SpatialDataPackageExport.44_2.zip](https://github.com/cividi/spatial-data-package-export/files/6708846/SpatialDataPackageExport.44_2.zip)
> 
> 

Will give it a try and let you know.

**Review by n0rdlicht — APPROVED** [review]

**Pull request merged**
