### PR TITLE
Data licenses

### LINKED ISSUE #19: UI for setting snapshot license
**Expected behaviour**
A dropdown to select the license of the snapshot. If licenses inside the metadata for a layer is set, add the license(s) to the resources when exporting.

**Current behaviour**
Uses default license from plugin template.

### PR DESCRIPTION
**Pull request by Joonalai**
This PR utilizes QGIS layer metadata licenses (into `snapshot.licenses`) and allows uses to select license for the whole Snapshot (into `snapshot.license`).

This PR also modifies model by removing `snapshot.license` and adding `License.title`.

WIP:
- [x] rebase after #29 is merged

Resolves #19.

### CODE REVIEW

**Comment by Joonalai** [comment]
@n0rdlicht this is now ready for review.

**Review by n0rdlicht — CHANGES_REQUESTED** [review]
The resulting `snapshot.licenses` would need to be wrapped in an array as well, otherwise everything checks out.

**Comment by Joonalai** [comment]
> The resulting `snapshot.licenses` would need to be wrapped in an array as well, otherwise everything checks out.

Makes sense! Sorry I misunderstood you previously :)

**Comment by Joonalai** [comment]
@n0rdlicht done!

**Comment by n0rdlicht** [comment]
When loading the current PR version I get.

```
2020-12-04T14:25:41     WARNING    Traceback (most recent call last):
              File "/home/thorben/.local/share/QGIS/QGIS3/profiles/gemeindescan/python/plugins/SpatialDataPackageExport/plugin.py", line 167, in run
              self.dock_widget = ExporterDockWidget(self.iface)
              File "/home/thorben/.local/share/QGIS/QGIS3/profiles/gemeindescan/python/plugins/SpatialDataPackageExport/ui/dock_widget.py", line 83, in __init__
              self.__set_initial_values()
              File "/home/thorben/.local/share/QGIS/QGIS3/profiles/gemeindescan/python/plugins/SpatialDataPackageExport/ui/dock_widget.py", line 109, in __set_initial_values
              self.cb_license.setCurrentText(self.data_pkg_handler.snapshot_template.licenses.title)
             AttributeError: 'list' object has no attribute 'title'
             
2020-12-04T14:25:44     WARNING    Traceback (most recent call last):
              File "/home/thorben/.local/share/QGIS/QGIS3/profiles/gemeindescan/python/plugins/SpatialDataPackageExport/plugin.py", line 169, in run
              self.dock_widget.closingPlugin.connect(self.onClosePlugin)
             AttributeError: 'NoneType' object has no attribute 'closingPlugin'
```

**Comment by Joonalai** [comment]
> When loading the current PR version I get.
> 
> ```
> 2020-12-04T14:25:41     WARNING    Traceback (most recent call last):
>               File "/home/thorben/.local/share/QGIS/QGIS3/profiles/gemeindescan/python/plugins/SpatialDataPackageExport/plugin.py", line 167, in run
>               self.dock_widget = ExporterDockWidget(self.iface)
>               File "/home/thorben/.local/share/QGIS/QGIS3/profiles/gemeindescan/python/plugins/SpatialDataPackageExport/ui/dock_widget.py", line 83, in __init__
>               self.__set_initial_values()
>               File "/home/thorben/.local/share/QGIS/QGIS3/profiles/gemeindescan/python/plugins/SpatialDataPackageExport/ui/dock_widget.py", line 109, in __set_initial_values
>               self.cb_license.setCurrentText(self.data_pkg_handler.snapshot_template.licenses.title)
>              AttributeError: 'list' object has no attribute 'title'
>              
> 2020-12-04T14:25:44     WARNING    Traceback (most recent call last):
>               File "/home/thorben/.local/share/QGIS/QGIS3/profiles/gemeindescan/python/plugins/SpatialDataPackageExport/plugin.py", line 169, in run
>               self.dock_widget.closingPlugin.connect(self.onClosePlugin)
>              AttributeError: 'NoneType' object has no attribute 'closingPlugin'
> ```

Fixed!

**Review by n0rdlicht — APPROVED** [review]

**Pull request merged**
