### PR TITLE
Add snashot import support

### LINKED ISSUE #8: Load exported snapshots for editing
**Expected behaviour**
A way to open exported snapshots as QGIS layers and prefilled Spatial Data Package Export fields based on an existing snapshot.json.

**Current behaviour**
Not part of the MVP scope.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

### PR DESCRIPTION
**Pull request by Joonalai**
Note: This PR should definitely be squashed as merging.

This PR:

- Adds snapshot import support
- Updates qgis_plugin_tools
- Applies Black, isort, mypy and flake8 via pre-commit
- Updates workflows
- Adds support for rule based styling
import-spatia-data-package

Resolves #8.

### CODE REVIEW

**Comment by n0rdlicht** [comment]
🎉 will test and add my observations here. @Joonalai is it possible to trigger a pre-release build from this PR?

**Comment by Joonalai** [comment]
> tada will test and add my observations here. @Joonalai is it possible to trigger a pre-release build from this PR?

Yes, the pre-release is triggered automatically if all tests on different platforms succeed. My latest commit should fix all tests.

**Comment by Joonalai** [comment]
The pre-release workflow failed for reason, but here is a release you can test
[SpatialDataPackageExport.pr_46.zip](https://github.com/cividi/spatial-data-package-export/files/6552151/SpatialDataPackageExport.pr_46.zip)

**Comment by n0rdlicht** [comment]
> The pre-release workflow failed for reason, but here is a release you can test
> [SpatialDataPackageExport.pr_46.zip](https://github.com/cividi/spatial-data-package-export/files/6552151/SpatialDataPackageExport.pr_46.zip)

thanks. started a local build (not successfull yet :))

**Comment by n0rdlicht** [comment]
Currently met with the following error after installing from zip inside an instance that already had the current release version installed:

<pre>
An error has occurred while executing Python code: 

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 631: ordinal not in range(128) 
Traceback (most recent call last):
  File "/Users/thorben.cividi/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/SpatialDataPackageExport/plugin.py", line 163, in run
    self.dock_widget = ExporterDockWidget(self.iface)
  File "/Users/thorben.cividi/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/SpatialDataPackageExport/ui/dock_widget.py", line 93, in __init__
    self.data_pkg_handler = DataPackageHandler.create()
  File "/Users/thorben.cividi/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/SpatialDataPackageExport/core/datapackage.py", line 70, in create
    else DataPackageHandler.load_config_from_template()
  File "/Users/thorben.cividi/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/SpatialDataPackageExport/core/datapackage.py", line 103, in load_config_from_template
    return Config.from_dict(load_json(template_path))
  File "/Users/thorben.cividi/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/SpatialDataPackageExport/core/utils.py", line 29, in load_json
    template = json.load(f)
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/Applications/QGIS.app/Contents/MacOS/lib/python3.8/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 631: ordinal not in range(128)

Python version: 3.8.7 (default, Feb 10 2021, 09:04:08) [Clang 12.0.0 (clang-1200.0.32.29)] 
QGIS version: 3.18.1-Zürich Zürich, 202f1bf7e5 
</pre>

<details>
Python Path:
/Applications/QGIS.app/Contents/MacOS/../Resources/python
/Users/thorben.cividi/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/thorben.cividi/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS.app/Contents/MacOS/../Resources/python/plugins
/Applications/QGIS.app/Contents/MacOS/lib/python3.8
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/numpy-1.20.1-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/pyproj-2.6.0-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/geopandas-0.8.1-py3.8.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/pandas-1.1.0-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/snuggs-1.4.7-py3.8.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/patsy-0.5.1-py3.8.egg
/Applications/QGIS.app/Contents/MacOS/lib/python38.zip
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/numba-0.50.1-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/rasterio-1.1.5-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/cftime-1.2.1-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/Rtree-0.9.4-py3.8.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/matplotlib-3.3.0-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/GDAL-3.2.1-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/lib-dynload
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/Pillow-7.2.0-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/affine-2.3.0-py3.8.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/statsmodels-0.11.1-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/click_plugins-1.1.1-py3.8.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/netCDF4-1.5.4-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/Fiona-1.8.13.post1-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/scipy-1.5.1-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/opencv_contrib_python-4.3.0.36-py3.8-macosx-10.13.0-x86_64.egg
/Users/thorben.cividi/Library/Application Support/QGIS/QGIS3/profiles/default/python
</details>

**Comment by n0rdlicht** [comment]
Replaced export-config.json with current one (had an unescaped © in there), now the load error is gone :)

**Comment by n0rdlicht** [comment]
Similar issues pops up when opening snapshots that have unescaped non ascii characters and are saved as utf-8 encoded files.

> 2021-05-27T10:47:50     INFO    Importing snapshot something-v4.json
> 2021-05-27T10:47:50     CRITICAL    Uncaught error occurred
> 2021-05-27T10:47:50     CRITICAL    'ascii' codec can't decode byte 0xc3 in position 91: ordinal not in range(128)

Character in the file: ä.

**Comment by Joonalai** [comment]
How the non ascii characters are presented in the snapshots?

**Comment by n0rdlicht** [comment]
> How the non ascii characters are presented in the snapshots?

How do they get in or how they are rendered on the platform?
- How they get in: manual editing of the json or other software generating the files
- How the get rendered: looking at an example it seems that Django/Graphene are normalizing these into utf-8 only strings when reading the json stored on disk

example excerpt from a snapshot on disk (utf-8 encoded file)
```json
{
...
   "description": "Dargestellt ist die h\u00e4ufigste Arbeitsplatzkategorie je 100 x 100m über 5 Jahre.",
...
}
```

after upload how it is delivered to the browser via the API
```json
{
...
   "description": "Dargestellt ist die häufigste Arbeitsplatzkategorie je 100 x 100m über 5 Jahre.",
...
}
```

html source of page showing
```html
<p>Dargestellt ist die häufigste Arbeitsplatzkategorie je 100 x 100m über 5 Jahre.</p>
```

**Comment by n0rdlicht** [comment]
I did some further testing with plugin exported snapshots (no encoding issues on this end).

A couple of scope questions/thoughts mostly related to re-exportability of an imported snapshot:
- Do you see an option to import snapshots as utf-8 / translating unicode encoded special characters?
- Is there a way to make the imported symbol classes discrete? E.g. combine them into unique symbols with an internal symbol id applied to the matching features rather than a symbol per feature, as a step 2 we could fetch the legend text for these symbols from `views[0].spec.legend[x].label`, though this might lead to collisions if different layers use the same style
- Could we "re-import" the background map layer (if existing) as a WMS layer?
  - Option 1: turn a mapbox style url (`resource.mediatype: application/vnd.mapbox-vector-tile`)with the following `resource.path` `mapbox://styles/{user}/{styleId}` into the corresponding mapbox WMS endpoint like this `https://api.mapbox.com/styles/v1/{user}/{styleId}/wmts?access_token={mapbox access token}`. Only thing missing here would be the access token that could be would need to be added in the plugin settings. 
  - Option 2: when importing a snapshot add a the mapbox style defined in `templates/snapshot-template.json`

**Comment by Joonalai** [comment]
> I did some further testing with plugin exported snapshots (no encoding issues on this end).
> 
> A couple of scope questions/thoughts mostly related to re-exportability of an imported snapshot:
> 
>     * Do you see an option to import snapshots as utf-8 / translating unicode encoded special characters?

This is being fixed as we speak by @LKajan. I think this PR should be ready by then.

>     * Is there a way to make the imported symbol classes discrete? E.g. combine them into unique symbols (same style attributes = unique symbol) with an internal symbol id applied to the matching features rather than a symbol per feature, as a step 2 we could fetch the legend text for these symbols from `views[0].spec.legend[x].label`, though this might lead to collisions if different layers use the same style

This is more complex case. I think a separate issue should be made from this. I think one big problem is that it is hard to identify which legend entry belongs to which layer.

>     * Could we "re-import" the background map layer (if existing) as a WMS layer?
>       * Option 1: turn a mapbox style url (`resource.mediatype: application/vnd.mapbox-vector-tile`)with the following `resource.path` `mapbox://styles/{user}/{styleId}` into the corresponding mapbox WMS endpoint like this `https://api.mapbox.com/styles/v1/{user}/{styleId}/wmts?access_token={mapbox access token}`. Only thing missing here would be the access token that could be would need to be added in the plugin settings.
>       * Option 2: when importing a snapshot add a the mapbox style defined in `templates/snapshot-template.json`

This could definitely be done! I think that option 1 would be better and we have actually done something similar with a different plugin. I think a separate issue should be made for this as well.

**Pull request merged**
